#!/bin/bash
#set -e
#root_dir=`pwd`
root_dir=/usr/local/tt
ags=$*
so=0
while getopts :i:o:e:l:f opt
do
 case $opt in
 i) ;;
 o) ;;
 l) ;;
 e) ;;
 s);;
 f) so=1 ;;
 *) echo $opt not a option;;
 esac
done

shift $[$OPTIND-1]
if test $so -eq 0
then
	if test $# -gt 0
	then
		strace -c -f  -o $root_dir/data/tmp $*
	fi
	
fi
python $root_dir/ctl.py -d $root_dir $ags
